In [1]:
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch.optim as optim
from torch.autograd import Variable
import torch
from tqdm import tqdm
import sys

In [2]:
from torch.utils.tensorboard import SummaryWriter

In [3]:
sys.path.insert(0,'..')
import bitmap
import itertools
from forward_prediction import forward_model

# Generate data

## Training data

In [98]:
regenerate_data = False

In [99]:
# Generate or load training data
N = 51200

if regenerate_data:
    train_data_gen = bitmap.generate_train_set(N, 41, min_delta=1, max_delta=1)
    deltas, start_boards, stop_boards = map(np.array, zip(*list(train_data_gen)))
    # Save training data
    np.save('../../data/training_start_boards', start_boards)
    np.save('../../data/training_stop_boards', stop_boards)
else:
    start_boards = np.load('../../data/training_start_boards.npy')
    stop_boards = np.load('../../data/training_stop_boards.npy')

## Validation data

In [100]:
# Generate or load validation data
N_valid = 12800

if regenerate_data:
    valid_data_gen = bitmap.generate_train_set(N_valid, 1024, min_delta=1, max_delta=1)
    deltas, valid_start_boards, valid_stop_boards = map(np.array, zip(*list(valid_data_gen)))
    # Save validation data
    np.save('../../data/valid_start_boards', valid_start_boards)
    np.save('../../data/valid_stop_boards', valid_stop_boards)
else:
    valid_start_boards = np.load('../../data/valid_start_boards.npy')
    valid_stop_boards = np.load('../../data/valid_stop_boards.npy')

In [101]:
X_valid = Variable(torch.tensor(valid_start_boards).view(N_valid, 1, 25, 25).float())
y_valid = Variable(torch.tensor(valid_stop_boards).view(N_valid, 1, 25, 25).float())

## Test data

In [102]:
# Generate or load test data
N_test = 25600

if regenerate_data:
    test_data_gen = bitmap.generate_train_set(N_test, 42, min_delta=1, max_delta=1)
    deltas, test_start_boards, test_stop_boards = map(np.array, zip(*list(test_data_gen)))
    # Save test data
    np.save('../../data/test_start_boards', test_start_boards)
    np.save('../../data/test_stop_boards', test_stop_boards)
else:
    test_start_boards = np.load('../../data/test_start_boards.npy')
    test_stop_boards = np.load('../../data/test_stop_boards.npy')

# Model trainer

In [103]:
def train(model, X, y, X_valid, y_valid, 
          optim, criterion, output_path, num_epochs=50, batch_size=128):
    # Release CUDA memory
    torch.cuda.empty_cache()

    # Set optimizer
    optimizer = optim(model.parameters())
    
    # Setup Tensorboard (https://pytorch.org/docs/stable/tensorboard.html)
    writer = SummaryWriter()
    writer.add_graph(model.cpu(), X)
    model.cuda()

    # Best validation MAE
    best_valid_mae = 1
    
    # Train
    n_iter = 0
    for epoch in range(num_epochs): 
        permutation = torch.randperm(X.size()[0])
        running_loss = 0.0
        pbar = tqdm(range(0, X.size()[0], batch_size))
        for i in pbar:
            n_iter += 1
            indices = permutation[i:i+batch_size]
            batch = X[indices].cuda()
            target = y[indices].cuda()
        
            optimizer.zero_grad()
            outputs = model(batch)
            loss = criterion(outputs, target)
            loss.backward()
            optimizer.step()
            pbar.set_description("[{:d}, {:5d}] loss: {:.8f}".format(epoch + 1, i + 1, loss.item()))    
            
            # Calculate MAE
            output_boards = (outputs > 0.5).int()
            mae = torch.sum(output_boards != target) / (batch_size * 25 * 25)
            
            # Write data to Tensorboard
            writer.add_scalar('Loss/train', loss.item(), n_iter)
            writer.add_scalar('MAE/train', mae.item(), n_iter)
            
            # Write boards and validation results to Tensorboard every 50 batches
            if n_iter % 50 == 0:
                with torch.no_grad():
                    model.eval()
                    valid_loss = 0
                    valid_mae = 0
                    m = 0
                    for j in range(0, X_valid.size()[0], batch_size):
                        m += 1
                        valid_batch = X_valid[j:j+batch_size].cuda()
                        valid_target = y_valid[j:j+batch_size].cuda()
                        valid_outputs = model(valid_batch)
                        valid_loss += criterion(valid_outputs, valid_target)
                        valid_boards = (valid_outputs > 0.5).int()
                        valid_mae += torch.sum(valid_boards != valid_target).float()
                    valid_loss /= m
                    valid_mae /= (X_valid.size()[0] * 25 * 25)
                    writer.add_image('predicted stop board', valid_boards[-1], n_iter)
                    writer.add_image('actual stop board', y_valid[-1], n_iter)
                    writer.add_scalar('Loss/valid', valid_loss.item(), n_iter)
                    writer.add_scalar('MAE/valid', valid_mae.item(), n_iter)
                    
                if valid_mae < best_valid_mae:
                    best_valid_mae = valid_mae
                    # Save model if we have the lastest best MAE
                    torch.save(model.state_dict(), output_path)
    writer.close()
    print("The best validation MAE: {}".format(best_valid_mae))

# Train a forward network

In [104]:
class ForwardNet(nn.Module):
    def __init__(self):
        super(ForwardNet, self).__init__()
        # in channels, out channels, kernel size
        self.conv1 = nn.Conv2d(1, 16, (3, 3), padding=(1, 1), padding_mode='circular')
        self.activ1 = nn.ReLU()
        self.conv2 = nn.Conv2d(16, 8, (3, 3), padding=(1, 1), padding_mode='circular')
        self.activ2 = nn.PReLU()
        self.conv3 = nn.Conv2d(8, 4, (3, 3), padding=(1, 1), padding_mode='circular')
        self.activ3 = nn.PReLU()
        self.conv4 = nn.Conv2d(4, 1, (3, 3), padding=(1, 1), padding_mode='circular')
        
    def forward(self, x):
        x = self.activ1(self.conv1(x))
        x = self.activ2(self.conv2(x))
        x = self.activ3(self.conv3(x))
        x = torch.sigmoid(self.conv4(x))
        return x

In [105]:
forward_net = ForwardNet()
criterion = nn.BCELoss()

In [106]:
X = Variable(torch.tensor(start_boards[:25600]).view(25600, 1, 25, 25).float(), requires_grad=True)
y = Variable(torch.tensor(stop_boards[:25600]).view(25600, 1, 25, 25).float())

In [108]:
vanilla_forward_model_path = "../models/johnson/vanilla_forward.pkl"
forward_net.load_state_dict(torch.load(vanilla_forward_model_path));

### Uncomment below to retrain forward model with warm start

In [ ]:
# train(forward_net, X, y, X_valid, y_valid, optim.Adam, criterion, vanilla_forward_model_path, num_epochs=30)

In [109]:
def get_forward_mae(model, weight_path, start_boards, stop_boards, n):
    # Release CUDA memory
    torch.cuda.empty_cache()
    # Load model
    model.load_state_dict(torch.load(weight_path))
    model.cuda()
    # Convert boards to tensor
    start_boards_tensor = torch.tensor(start_boards[:n]).view(n, 1, 25, 25).float().cuda()
    stop_boards_tensor = torch.tensor(stop_boards[:n]).view(n, 1, 25, 25)
    with torch.no_grad():
        model.eval()
        # Make prediction
        predicted_stop_board = (model(start_boards_tensor) > 0.5).int().cpu()
        error = torch.sum(predicted_stop_board != stop_boards_tensor)
        # print(predicted_stop_board)
        # print(stop_boards_tensor)
        return error / (n * 25 * 25)

In [110]:
# Training data MAE
train_mae = get_forward_mae(forward_net, vanilla_forward_model_path, 
                            start_boards, stop_boards, 25600)
print("The training data MAE is {:.8f}.".format(train_mae))

# Test data MAE
test_mae = get_forward_mae(forward_net, vanilla_forward_model_path,
                           test_start_boards, test_stop_boards, N_test)
print("The test data MAE is {:.8f}.".format(test_mae))

The training data MAE is 0.00000000.
The test data MAE is 0.00000000.


# Relax starting boards

In [111]:
# Modify starting boards 
def relax_boards(boards):
    np.random.seed(41)
    return np.abs(np.random.rand(*boards.shape) / 2 - boards)

In [112]:
relaxed_start_boards = relax_boards(start_boards)

In [113]:
class RelaxedForwardNet(nn.Module):
    def __init__(self):
        super(RelaxedForwardNet, self).__init__()
        # in channels, out channels, kernel size
        self.conv0 = nn.Conv2d(1, 8, (1, 1))
        self.activ0 = nn.ReLU()
        self.conv1 = nn.Conv2d(8, 16, (3, 3), padding=(1, 1), padding_mode='circular')
        self.activ1 = nn.PReLU()
        self.conv2 = nn.Conv2d(16, 8, (3, 3), padding=(1, 1), padding_mode='circular')
        self.activ2 = nn.PReLU()
        self.conv3 = nn.Conv2d(8, 4, (3, 3), padding=(1, 1), padding_mode='circular')
        self.activ3 = nn.PReLU()
        self.conv4 = nn.Conv2d(4, 1, (3, 3), padding=(1, 1), padding_mode='circular')
        
    def forward(self, x):
        x = self.activ0(self.conv0(x))
        x = self.activ1(self.conv1(x))
        x = self.activ2(self.conv2(x))
        x = self.activ3(self.conv3(x))
        x = torch.sigmoid(self.conv4(x))
        return x

In [114]:
relaxed_forward_net = RelaxedForwardNet()
criterion = nn.BCELoss()

In [115]:
X_relaxed = Variable(torch.tensor(relaxed_start_boards).view(N, 1, 25, 25).float(), requires_grad=True)
y = Variable(torch.tensor(stop_boards).view(N, 1, 25, 25).float())

In [116]:
relaxed_valid_start_boards = relax_boards(valid_start_boards)
X_valid_relaxed = Variable(torch.tensor(relaxed_valid_start_boards).view(N_valid, 1, 25, 25).float())

In [96]:
relaxed_forward_model_path = "../models/johnson/relaxed_forward.pkl"
relaxed_forward_net.load_state_dict(torch.load(relaxed_forward_model_path))

[30, 51073] loss: 13.36499977: 100%|██████████| 400/400 [00:22<00:00, 17.79it/s]

The best validation MAE: 0.0034505000803619623


### Uncomment below to retrain _relaxed_ forward model with warm start

In [ ]:
# train(relaxed_forward_net, X_relaxed, y, X_valid_relaxed, y_valid, optim.Adam, criterion, relaxed_forward_model_path, num_epochs=30)

In [97]:
# Training data MAE
train_mae = get_forward_mae(relaxed_forward_net, relaxed_forward_model_path, relaxed_start_boards, stop_boards, N)
print("The training data MAE is {:.6f}.".format(train_mae))

# Test data MAE
relaxed_test_start_boards = relax_boards(test_start_boards)
test_mae = get_forward_mae(relaxed_forward_net, relaxed_forward_model_path, relaxed_test_start_boards, test_stop_boards, N_test)
print("The test data MAE is {:.6f}.".format(test_mae))

The training data MAE is 0.003387.
The test data MAE is 0.003402.


In [95]:
relaxed_forward_net.state_dict()

OrderedDict([('conv0.weight',
              tensor([[[[-1.2373]]],
              
              
                      [[[ 0.5089]]],
              
              
                      [[[ 1.7855]]],
              
              
                      [[[ 0.0132]]],
              
              
                      [[[-0.7155]]],
              
              
                      [[[ 0.6486]]],
              
              
                      [[[ 0.3530]]],
              
              
                      [[[ 0.6423]]]], device='cuda:0')),
             ('conv0.bias',
              tensor([ 0.6645, -0.2445,  0.5337, -0.4339, -0.9760, -0.3080, -0.6959, -0.9832],
                     device='cuda:0')),
             ('conv1.weight',
              tensor([[[[-5.7794e-02, -1.9391e-01,  1.2345e-01],
                        [-1.9683e-01, -2.5391e-01, -2.9529e-01],
                        [-2.5443e-01, -3.0142e-01, -4.2866e-02]],
              
                       [[ 1.0292e-01,  2

# Reverse model

In [ ]:
class ReverseNet(nn.Module):
    def __init__(self):
        super(ReverseNet, self).__init__()
        # in channels, out channels, kernel size
        self.conv1 = nn.Conv2d(1, 16, (5, 5), padding=(2, 2), padding_mode='circular')
        self.activ1 = nn.PReLU()
        self.conv2 = nn.Conv2d(16, 8, (5, 5), padding=(2, 2), padding_mode='circular')
        self.activ2 = nn.PReLU()
        self.conv3 = nn.Conv2d(8, 4, (3, 3), padding=(1, 1), padding_mode='circular')
        self.activ3 = nn.PReLU()
        self.conv4 = nn.Conv2d(4, 1, (3, 3), padding=(1, 1), padding_mode='circular')

    def forward(self, x):
        x = self.reverse(x)
        return x

    def reverse(self, x):
        x = self.activ1(self.conv1(x))
        x = self.activ2(self.conv2(x))
        x = self.activ3(self.conv3(x))
        x = torch.sigmoid(self.conv4(x))
        return x

In [ ]:
net = ReverseNet()
print(net)

In [ ]:
criterion = nn.BCELoss()
optimizer = optim.Adam(net.parameters()) #, lr=0.001, momentum=0.9)

In [ ]:
X = Variable(torch.tensor(stop_boards).view(N, 1, 25, 25).float(), requires_grad=True)
y = Variable(torch.tensor(start_boards).view(N, 1, 25, 25).float())
num_epochs = 50
batch_size = 128
for epoch in tqdm(range(num_epochs)): 
    permutation = torch.randperm(X.size()[0])
    running_loss = 0.0
    for i in range(0, X.size()[0], batch_size):
        indices = permutation[i:i+batch_size]
        batch = X[indices]
        target = y[indices]
        
        optimizer.zero_grad()
        outputs = net(batch)
        # loss = criterion(outputs, batch)
        loss = criterion(outputs, target)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        if i % 1000 == 0 and i > 0:
            print('[%d, %5d] loss: %.3f' % (epoch + 1, i + 1, running_loss / 10))
        running_loss = 0.0

In [ ]:
# Generate testing data
N_test = 25600
# test_data_gen = bitmap.generate_test_set(N_test, 45, max_delta=1)
test_data_gen = bitmap.generate_test_set(N_test, 45, min_delta=5, max_delta=5)
delta, test_stop_boards = map(list, zip(*list(test_data_gen)))

In [ ]:
def get_mae(stop_boards, n, delta=1):
    stop_boards_tensor = torch.tensor(stop_boards).view(n, 1, 25, 25).float()
    with torch.no_grad():
        net.eval()
        # Make prediction
        output = (net(stop_boards_tensor) > 0.5).int()
        # Evolve one step forward
        predicted_stop_board = output
        for _ in range(delta):
            predicted_stop_board = (forward_model.forward(predicted_stop_board) > 0.5).int()
        error = torch.sum(predicted_stop_board != stop_boards_tensor.int())
        return error / (n * 25 * 25)

In [ ]:
# Training data MAE
train_mae = get_mae(stop_boards, N, 5).item()
print("The training data MAE is {:.6f}.".format(train_mae))

# Test data MAE
test_mae = get_mae(test_stop_boards, N_test, 5).item()
print("The test data MAE is {:.6f}.".format(test_mae))

In [ ]:
# Test data MAE
test_mae = get_mae(test_stop_boards, N_test, 5).item()
print("The test data MAE is {:.6f}.".format(test_mae))

# Appendix: CUDA memory management

In [ ]:
torch.cuda.memory_summary()

In [ ]:
torch.cuda.memory_snapshot()